name: treblekit
description: "TrebleKit"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freefeos:
    path: ../../FlutterProjects/freefeos
  multi_builder: ^1.3.0
  flutter_plugin_android_lifecycle: ^2.0.32
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: io.treblekit.flutter
